### ISSUE TITLE
Login with Meetup.com

### ISSUE THREAD

**Issue by labradford** [gdisd/volunteer_manager#29]
GDISD uses Meetup.com to manage it's membership. Users should be able to login with their Meetup.com credentials.
There's a gem for that:
https://github.com/tapster/omniauth-meetup

**Comment by Brazilgabe** [comment]
User now has the ability to login with meet up

**Comment by Brazilgabe** [comment]
Remaining issues are:
1. Create a meet up account for testing
2. Update document with new meet up information (key, secret)
3. Add another section on the home page for Meetup login (currently lists Signup or Login)
