### ISSUE TITLE
Update about page with GDI San Diego leadership

### ISSUE THREAD

**Issue by labradford** [gdisd/volunteer_manager#35]
Add Shana and Courtney's bios and photos from 
https://www.girldevelopit.com/chapters/san-diego
FROM BOTTOM SECTION "Leaders"
Add css styles to match the style of this page

**Comment by Brazilgabe** [comment]
Shana & Courtney's bio has been added along with styles,
application.scss still needs to be edited so that all headers are consistent.
Pull request has been created.
