### ISSUE TITLE
Update Navbar css 

### ISSUE THREAD

**Issue by labradford** [gdisd/volunteer_manager#36]
Match the style of the GDI website navbar:
https://www.girldevelopit.com/
The goal is to have it be seemless looking when navigating between the app and the GDI site

**Comment by labradford** [comment]
Add a css file to the asset pipeline call it navbar.scss and add navbar styles to it.

**Comment by Brazilgabe** [comment]
Issues Remaining..
Navbar will not accept Font-weight of 300,
Navbar link needs to be highlighted with its respected page.
