### ISSUE TITLE
Update CSS for app Headers and paragraph text

### ISSUE THREAD

**Issue by labradford** [gdisd/volunteer_manager#37]
Setup default paragraph and heading styles to match the GDI site.
Fonts, Colors, links, etc. 
Add to app/assets/stylesheets/applications.scss

**Comment by labradford** [comment]
Completed by Gabe - pull request merged

**Comment by Brazilgabe** [comment]
Need to talk about whether we will be styling each page as an individual or will we attempt to target all headers, paragraphs and etc.. with the same style.
